apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ .Values.backend.name }}
